### ISSUE TITLE
*ST股获取不到

### ISSUE THREAD

**Issue by qiuyuxuan1999** [georgezhao2010/tencent_stock#1]
发现应该是个bug，经过多次测试，发现星*ST的股票抓取不到，如图。是不是因为这个*导致无法读取？
![Screenshot_20210928_201808_io homeassistant companion android](https://user-images.githubusercontent.com/64347554/135086377-bd41083d-972f-42a3-95e9-f940733f2680.jpg)

**Comment by georgezhao2010** [comment]
> 发现应该是个bug，经过多次测试，发现星_ST的股票抓取不到，如图。是不是因为这个_导致无法读取？ !

v0.0.5已解决问题
